name: github-linux

on: [push, pull_request]

jobs:
  linux-release-serial:
    # simple serial release build using g++

    name: linux release serial
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        ./contrib/utilities/download_clang_format
    - name: info
      run: |
        g++ -v
        cmake --version
    - name: configure
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -D DEAL_II_CXX_FLAGS='-Werror' .
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: linux-serial-detailed.log
        path: detailed.log
    - name: build
      run: |
        ./contrib/utilities/check_indentation.sh
        make -j 2
